/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

int gamegrad(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int gamegrad_alloc_mem(void);
int gamegrad_init_mem(int mem);
void gamegrad_free_mem(int mem);
int gamegrad_checkout(void);
void gamegrad_release(int mem);
void gamegrad_incref(void);
void gamegrad_decref(void);
casadi_int gamegrad_n_in(void);
casadi_int gamegrad_n_out(void);
casadi_real gamegrad_default_in(casadi_int i);
const char* gamegrad_name_in(casadi_int i);
const char* gamegrad_name_out(casadi_int i);
const casadi_int* gamegrad_sparsity_in(casadi_int i);
const casadi_int* gamegrad_sparsity_out(casadi_int i);
int gamegrad_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
int gamehess(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem);
int gamehess_alloc_mem(void);
int gamehess_init_mem(int mem);
void gamehess_free_mem(int mem);
int gamehess_checkout(void);
void gamehess_release(int mem);
void gamehess_incref(void);
void gamehess_decref(void);
casadi_int gamehess_n_in(void);
casadi_int gamehess_n_out(void);
casadi_real gamehess_default_in(casadi_int i);
const char* gamehess_name_in(casadi_int i);
const char* gamehess_name_out(casadi_int i);
const casadi_int* gamehess_sparsity_in(casadi_int i);
const casadi_int* gamehess_sparsity_out(casadi_int i);
int gamehess_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
#ifdef __cplusplus
} /* extern "C" */
#endif
